const baseUrl = 'https://notes-com-backend.onrender.com/api/v1/'

export const getNotesApi = baseUrl+'notes/getNotes'
export const logInApi = baseUrl+'users/login'
export const signInApi = baseUrl+'users/register'
export const uploadNoteApi = baseUrl+'notes/upload'
export const logOutApi = baseUrl+'users/logout'
export const deleteApi = baseUrl+'notes/deleteNote'
export const applyManagerApi = baseUrl+'users/applyManager'
export const myNotesApi = baseUrl+'notes/myNotes'
